export const APP_CONFIG = {
  name: 'Cambuci Mobile',
  legalName: 'Cambuci Mobile LTDA',
  tagline: 'Assistência técnica especializada em celulares, ordens de serviço e vendas',
  version: '4.1.0',
  description:
    'Cambuci Mobile é o sistema completo para controle de ordens de serviço (OS), status de reparo em tempo real, orçamento de peças/mão de obra e CRM para assistência técnica de celulares.',
  supportEmail: 'contato@cambucimobile.com.br',
  defaultCurrency: 'BRL' as const,
  defaultHourlyRate: 80,
  storagePrefix: 'cambucimobile_v1',
  brand: {
    primary: '#0055FF',
    gold: '#FFD100',
    ink: '#0B1633',
    paper: '#F5F7FA',
    logo: '/brand/logo.png',
    logoMark: '/brand/logo-mark.jpg',
    hero: '/brand/hero.jpg',
    pattern: '/brand/pattern.jpg',
    product: '/brand/product.jpg',
  },
  pagination: {
    defaultPageSize: 10,
    pageSizeOptions: [5, 10, 25, 50],
  },
} as const;

export const ROUTES = {
  home: '/',
  statusPortal: '/status',
  statusDetail: (id: string) => `/status/${id}`,
  auth: {
    login: '/login',
    register: '/register',
    callback: '/auth/callback',
  },
  app: {
    root: '/app',
    dashboard: '/app/dashboard',
    orders: '/app/orders',
    ordersNew: '/app/orders/new',
    orderDetail: (id: string) => `/app/orders/${id}`,
    devices: '/app/devices',
    inventory: '/app/inventory',
    pos: '/app/pos',
    clients: '/app/clients',
    clientsNew: '/app/clients/new',
    clientDetail: (id: string) => `/app/clients/${id}`,
    calculator: '/app/calculator',
    team: '/app/team',
    warranties: '/app/warranties',
    settings: '/app/settings',
    profile: '/app/profile',
  },
  designSystem: '/design-system',
} as const;
